import { expect, test } from '@playwright/test';

test.describe('Internationalization', () => {
  test('the default locale for a Spanish-locale browser is Spanish', async ({ browser }) => {
    // Browsers always send an Accept-Language header, so the next-intl
    // middleware negotiates a locale from there. Setting the browser locale
    // to es-ES is the closest we can get to "no preference" in a way that
    // exercises the real codepath.
    const ctx = await browser.newContext({ locale: 'es-ES' });
    const page = await ctx.newPage();
    await page.goto('/', { waitUntil: 'commit' });
    await expect(page.locator('html')).toHaveAttribute('lang', 'es', { timeout: 10_000 });
    await ctx.close();
  });

  test('English locale is reachable at /en and renders English copy', async ({ page }) => {
    await page.goto('/en');
    await expect(page).toHaveURL(/\/en\/?$/);
    await expect(page.locator('html')).toHaveAttribute('lang', 'en');
    await expect(page.locator('html')).toHaveAttribute('dir', 'ltr');
    // The English home should show a heading containing "Welcome".
    await expect(page.getByRole('heading', { level: 1 })).toContainText(/welcome/i);
  });

  test('Arabic locale flips the document direction to RTL', async ({ page }) => {
    await page.goto('/ar');
    await expect(page).toHaveURL(/\/ar\/?$/);
    await expect(page.locator('html')).toHaveAttribute('lang', 'ar');
    await expect(page.locator('html')).toHaveAttribute('dir', 'rtl');
  });

  test('Accept-Language header steers the middleware to the right locale', async ({ browser }) => {
    // Override the browser's default Accept-Language header so the test
    // is deterministic across Chromium versions.
    const ctx = await browser.newContext({ locale: 'pt-BR' });
    const page = await ctx.newPage();
    await page.goto('/', { waitUntil: 'commit' });
    // The middleware picks Portuguese (pt) from the Accept-Language header
    // generated by setting the browser locale to pt-BR.
    await expect(page.locator('html')).toHaveAttribute('lang', 'pt', { timeout: 10_000 });
    await ctx.close();
  });

  test('Switching locale preserves the current path (course -> /en/courses)', async ({ page }) => {
    await page.goto('/courses');
    // Locate the language switcher and switch to English.
    const enLink = page
      .locator('header a[href*="/en/"], a[hreflang="en"], a[href$="/en/"]')
      .first();
    if (await enLink.isVisible({ timeout: 3000 }).catch(() => false)) {
      await enLink.click();
      await expect(page).toHaveURL(/\/en\/courses/);
      await expect(page.locator('html')).toHaveAttribute('lang', 'en');
    } else {
      // No header switcher — navigate explicitly.
      await page.goto('/en/courses');
      await expect(page).toHaveURL(/\/en\/courses/);
    }
  });

  test('Japanese locale renders without crashing', async ({ page }) => {
    const r = await page.goto('/ja');
    expect(r?.status()).toBe(200);
    await expect(page.locator('html')).toHaveAttribute('lang', 'ja');
  });

  test('Chinese locale renders without crashing', async ({ page }) => {
    const r = await page.goto('/zh');
    expect(r?.status()).toBe(200);
    await expect(page.locator('html')).toHaveAttribute('lang', 'zh');
  });
});
