import { type CourseContent, type LearningPath, getExamHeader } from '@academy/content';

/**
 * Build the downloadable study-guide Markdown for a learning path.
 * Pure function — the API route is a thin wrapper around it.
 */
export function buildStudyGuide(path: LearningPath, course: CourseContent): string {
  const lines: string[] = [
    `# ${path.title} — Study Guide`,
    '',
    path.description,
    '',
    `Prepares for: **${path.externalExam}**`,
    '',
  ];

  path.levels.forEach((level, li) => {
    lines.push(`## Level ${li + 1}: ${level.title}`, '', level.description, '');
    for (const pu of level.units) {
      const unit = course.units.find((u) => u.slug === pu.unit);
      const lessons = unit?.lessons ?? [];
      const minutes = lessons.reduce((acc, l) => acc + (l.estimatedMinutes ?? 10), 0);
      lines.push(`### ${unit?.title ?? pu.unit} (~${minutes} min)`);
      if (pu.objectives.length > 0) {
        lines.push('', 'Objectives:');
        for (const o of pu.objectives) lines.push(`- [ ] ${o}`);
      }
      if (lessons.length > 0) {
        lines.push('', 'Lessons:');
        for (const l of lessons) {
          lines.push(`- [ ] ${l.title} (~${l.estimatedMinutes ?? 10} min)`);
        }
      }
      const labs = unit?.labs ?? [];
      if (labs.length > 0) {
        lines.push('', 'Labs:');
        for (const lab of labs) lines.push(`- [ ] ${lab.title}`);
      }
      for (const exam of pu.exams) {
        const header = getExamHeader(exam.id);
        const required = exam.passingScore ?? header?.passingScore ?? 80;
        lines.push('', `Exam: **${exam.id}** — pass with ≥${required}%.`);
      }
      lines.push('');
    }
    if (level.milestoneExam) {
      const required =
        level.milestoneExam.passingScore ??
        getExamHeader(level.milestoneExam.id)?.passingScore ??
        80;
      lines.push(`Milestone exam: **${level.milestoneExam.id}** — pass with ≥${required}%.`, '');
    }
  });

  lines.push('---', '', 'Generated by Academy. Tick boxes as you complete each item.');
  return `${lines.join('\n')}\n`;
}
